logging.level.root=INFO
logging.level.local.redcare=DEBUG
spring.application.name=redcare-task
spring.jackson.property-naming-strategy=SNAKE_CASE
github.token=${GITHUB_TOKEN:}
github.ua=pkosaleu-test-agent